# Generated by Django 5.2.6 on 2025-09-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inquiry_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_title', models.CharField(max_length=100, verbose_name='제목')),
                ('user_content', models.TextField(verbose_name='내용')),
                ('userinquiry_at', models.TimeField(auto_now=True, verbose_name='작성일')),
            ],
        ),
    ]
