# Generated by Django 5.2.6 on 2025-09-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tm_account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="User profile picture",
                null=True,
                upload_to="profile_pics",
            ),
        ),
    ]
