# Generated by Django 5.2.6 on 2025-09-10 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BondHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('issuer', models.CharField(blank=True, max_length=150)),
                ('currency', models.CharField(choices=[('KRW', 'KRW'), ('USD', 'USD'), ('JPY', 'JPY'), ('EUR', 'EUR')], default='KRW', max_length=3)),
                ('face_amount', models.DecimalField(decimal_places=2, help_text='액면총액', max_digits=18)),
                ('coupon_rate', models.DecimalField(decimal_places=2, help_text='표면금리(%)', max_digits=5)),
                ('purchase_price_pct', models.DecimalField(decimal_places=3, help_text='매수가(액면가=100 기준)', max_digits=6)),
                ('current_price_pct', models.DecimalField(blank=True, decimal_places=3, help_text='현재가(선택)', max_digits=6, null=True)),
                ('maturity_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bond_holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DepositSaving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_type', models.CharField(choices=[('DEPOSIT', '예금'), ('SAVING', '적금')], max_length=16)),
                ('bank_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=150)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('annual_rate', models.DecimalField(decimal_places=2, help_text='연이율(%) 예: 3.50', max_digits=5)),
                ('compounding', models.CharField(choices=[('NONE', '미적용(단리)'), ('MONTHLY', '월복리'), ('QUARTERLY', '분기복리'), ('ANNUALLY', '연복리')], default='NONE', max_length=16)),
                ('start_date', models.DateField()),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('KRW', 'KRW'), ('USD', 'USD'), ('JPY', 'JPY'), ('EUR', 'EUR')], default='KRW', max_length=3)),
                ('current_value_manual', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_savings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.CharField(choices=[('KR', '국내'), ('US', '해외(미국)')], max_length=8)),
                ('ticker', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('average_price', models.DecimalField(decimal_places=4, help_text='매수평균단가 (거래통화)', max_digits=18)),
                ('currency', models.CharField(choices=[('KRW', 'KRW'), ('USD', 'USD'), ('JPY', 'JPY'), ('EUR', 'EUR')], default='KRW', max_length=3)),
                ('current_price', models.DecimalField(blank=True, decimal_places=4, help_text='현재가 (선택)', max_digits=18, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
