# Generated by Django 5.2.6 on 2025-09-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondholding',
            name='bond_code',
            field=models.CharField(blank=True, help_text='KRX 채권 코드/ISIN (pykrx 조회용)', max_length=32),
        ),
        migrations.AddField(
            model_name='bondholding',
            name='last_price_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockholding',
            name='last_price_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
