# Generated by Django 5.2.6 on 2025-09-10 23:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_assets', '0002_bondholding_bond_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BondPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('price_pct', models.DecimalField(decimal_places=3, max_digits=8)),
                ('source', models.CharField(blank=True, max_length=20)),
                ('bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='tm_assets.bondholding')),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DepositValueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_history', to='tm_assets.depositsaving')),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('source', models.CharField(blank=True, max_length=20)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='tm_assets.stockholding')),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
            },
        ),
    ]
