# Generated by Django 5.2.6 on 2025-09-14 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_assets', '0003_bondpricehistory_depositvaluehistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondholding',
            name='bond_code',
            field=models.CharField(blank=True, help_text='KRX 채권 코드/ISIN (pykrx 조회용)', max_length=32, verbose_name='채권코드'),
        ),
        migrations.AlterField(
            model_name='bondholding',
            name='coupon_rate',
            field=models.DecimalField(decimal_places=2, help_text='표면금리(%)', max_digits=5, verbose_name='표면금리(%)'),
        ),
        migrations.AlterField(
            model_name='bondholding',
            name='currency',
            field=models.CharField(choices=[('KRW', '원화(KRW)'), ('USD', '달러(USD)'), ('JPY', '엔(JPY)'), ('EUR', '유로(EUR)')], default='KRW', max_length=3, verbose_name='통화'),
        ),
        migrations.AlterField(
            model_name='bondholding',
            name='current_price_pct',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='현재가(선택)', max_digits=6, null=True, verbose_name='현재가(%)'),
        ),
        migrations.AlterField(
            model_name='bondholding',
            name='face_amount',
            field=models.DecimalField(decimal_places=2, help_text='액면총액', max_digits=18, verbose_name='액면총액'),
        ),
        migrations.AlterField(
            model_name='bondholding',
            name='issuer',
            field=models.CharField(blank=True, max_length=150, verbose_name='발행처'),
        ),
        migrations.AlterField(
            model_name='bondholding',
            name='maturity_date',
            field=models.DateField(verbose_name='만기일'),
        ),
        migrations.AlterField(
            model_name='bondholding',
            name='name',
            field=models.CharField(max_length=150, verbose_name='채권명'),
        ),
        migrations.AlterField(
            model_name='bondholding',
            name='purchase_price_pct',
            field=models.DecimalField(decimal_places=3, help_text='매수가(액면가=100 기준)', max_digits=6, verbose_name='매수가(%)'),
        ),
        migrations.AlterField(
            model_name='bondholding',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bond_holdings', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AlterField(
            model_name='depositsaving',
            name='annual_rate',
            field=models.DecimalField(decimal_places=2, help_text='연이율(%) 예: 3.50', max_digits=5, verbose_name='연이율(%)'),
        ),
        migrations.AlterField(
            model_name='depositsaving',
            name='bank_name',
            field=models.CharField(max_length=100, verbose_name='은행명'),
        ),
        migrations.AlterField(
            model_name='depositsaving',
            name='compounding',
            field=models.CharField(choices=[('NONE', '미적용(단리)'), ('MONTHLY', '월복리'), ('QUARTERLY', '분기복리'), ('ANNUALLY', '연복리')], default='NONE', max_length=16, verbose_name='복리 주기'),
        ),
        migrations.AlterField(
            model_name='depositsaving',
            name='currency',
            field=models.CharField(choices=[('KRW', '원화(KRW)'), ('USD', '달러(USD)'), ('JPY', '엔(JPY)'), ('EUR', '유로(EUR)')], default='KRW', max_length=3, verbose_name='통화'),
        ),
        migrations.AlterField(
            model_name='depositsaving',
            name='current_value_manual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='평가액(직접입력)'),
        ),
        migrations.AlterField(
            model_name='depositsaving',
            name='maturity_date',
            field=models.DateField(blank=True, null=True, verbose_name='만기일'),
        ),
        migrations.AlterField(
            model_name='depositsaving',
            name='principal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='원금'),
        ),
        migrations.AlterField(
            model_name='depositsaving',
            name='product_name',
            field=models.CharField(max_length=150, verbose_name='상품명'),
        ),
        migrations.AlterField(
            model_name='depositsaving',
            name='product_type',
            field=models.CharField(choices=[('DEPOSIT', '예금'), ('SAVING', '적금')], max_length=16, verbose_name='유형'),
        ),
        migrations.AlterField(
            model_name='depositsaving',
            name='start_date',
            field=models.DateField(verbose_name='시작일'),
        ),
        migrations.AlterField(
            model_name='depositsaving',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_savings', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AlterField(
            model_name='stockholding',
            name='average_price',
            field=models.DecimalField(decimal_places=4, help_text='매수평균단가 (거래통화)', max_digits=18, verbose_name='평단가'),
        ),
        migrations.AlterField(
            model_name='stockholding',
            name='currency',
            field=models.CharField(choices=[('KRW', '원화(KRW)'), ('USD', '달러(USD)'), ('JPY', '엔(JPY)'), ('EUR', '유로(EUR)')], default='KRW', max_length=3, verbose_name='통화'),
        ),
        migrations.AlterField(
            model_name='stockholding',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='현재가 (선택)', max_digits=18, null=True, verbose_name='현재가'),
        ),
        migrations.AlterField(
            model_name='stockholding',
            name='market',
            field=models.CharField(choices=[('KR', '국내'), ('US', '해외(미국)')], max_length=8, verbose_name='시장'),
        ),
        migrations.AlterField(
            model_name='stockholding',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='종목명'),
        ),
        migrations.AlterField(
            model_name='stockholding',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=18, verbose_name='수량'),
        ),
        migrations.AlterField(
            model_name='stockholding',
            name='ticker',
            field=models.CharField(max_length=20, verbose_name='티커/종목코드'),
        ),
        migrations.AlterField(
            model_name='stockholding',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_holdings', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
